### ISSUE TITLE
XHTML vs HTML

### ISSUE THREAD

**Issue by FullStackFlamingo** [BBCConnectedStudio/documentation#3]
Just a small thing; 
`<script src="http://www.bbc.co.uk/taster/pilot-lib.js" type="text/javascript" />`
should be 
`<script src="http://www.bbc.co.uk/taster/pilot-lib.js" type="text/javascript" ></script>`

Confused for there for a second as my document standard is HTML, not XHTML.

**Comment by crosslandwa** [comment]
Resolved. Thanks for pointing that out.
